apiVersion: v1
kind: Namespace
metadata:
  name: quota-demo
  labels:
    name: quota-demo
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo
  namespace: quota-demo
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: quota-demo
    namespace: quota-demo
    labels:
      app: quota-demo
spec:
    replicas: 4
    selector:
    matchLabels:
        app: quota-demo
    template:
    metadata:
        labels:
          app: quota-demo
    spec:
        containers:
        - name: nginx
        image: nginx:latest