apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-test-flask
    namespace: ci
    labels:
    app: backend-flask
spec:
    replicas: 1
    selector:
        matchLabels:
        app: backend-flask
    template:
        metadata:
        labels:
            app: backend-flask
    spec:
        containers:
        - name: flask-app
        image: backend-k8s-hands-on:v3
---
apiVersion: v1
kind: Service
metadata:
    name: my-service-flask
    namespace: ci
    labels: 
    app: flask-app
spec:
    type: ClusterIP  
    selector:
    app: backend-flask
    ports:
    - protocol: TCP
        port: 8080
        targetPort: 5001    